import {
  StyledArticleHead,
  StyledArticleSubhead,
  StyledCaption,
  StyledDiv,
  StyledH1,
  StyledH2,
  StyledH3,
  StyledH4,
  StyledH5,
  StyledLabel,
  StyledParagraph,
  StyledSpan,
  StyledSubTitle,
  StyledTitle,
} from './Typography.styled';

export default {
  h1: StyledH1,
  h2: StyledH2,
  h3: StyledH3,
  h4: StyledH4,
  h5: StyledH5,
  span: StyledSpan,
  body: StyledDiv,
  div: StyledDiv,
  p: StyledParagraph,
  title: StyledTitle,
  'sub-title': StyledSubTitle,
  label: StyledLabel,
  caption: StyledCaption,
  'article-head': StyledArticleHead,
  'article-subHead': StyledArticleSubhead,
};
